Add clang-format and whitespace-linter support; elaborate in README

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,25 +1,42 @@
 #!/bin/sh
-#
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
-#
-# To enable this hook, rename this file to "pre-commit".
 
-# if xeno contains downloaded directory, abort committing
 REPO_DIR=$(dirname $0)/../$(basename `git rev-parse --show-toplevel`)
 
-if [ ! -d $REPO_DIR/../.git-hooks ]; then
-	echo "[Error] You are not at repo root, not allowed to commit"
+echo "===== pre-commit starts ===== "
+# mandatory files: README and LICENSE
+echo "Checking mandatory files..."
+MANDATORY_FILES_CHECK=0
+if [ ! -f $REPO_DIR/README.md ]; then
+	echo "$REPO_DIR/README.md not found"
+	MANDATORY_FILES_CHECK=1
+fi
+if [ ! -f $REPO_DIR/LICENSE.txt ]; then
+	echo "$REPO_DIR/LICENSE.txt not found"
+	MANDATORY_FILES_CHECK=1
+fi
+if [ $MANDATORY_FILES_CHECK -ne 0 ]; then
 	exit 1
 fi
 
+# python script(s) in addition
+echo "Running whitespace check..."
+$REPO_DIR/.git/hooks/pre-commit-lint-whitespace.py $REPO_DIR
+if [ $? -ne 0 ]; then
+	exit 1
+fi
+which clang-format > /dev/null
+if [ $? -eq 0 ]; then
+	echo "Running clang-format in-place..."
+	$REPO_DIR/.git/hooks/pre-commit-clang-format.py
+else
+	echo "Tool clang-format not found; skip running it"
+fi
+# check if xeno/ contains downloaded directory
 if [ -f $REPO_DIR/xeno/fetch.py ]; then
 	echo "Checking xeno/fetch.py -q..."
 	$REPO_DIR/xeno/fetch.py -q
 	if [ $? -ne 0 ]; then
-		echo "xeno/ contains downloaded directory, should not be committed"
+		echo "xeno/ contains downloaded directory, abort committing"
 		exit 1
 	fi
 fi
@@ -34,33 +51,15 @@ fi
 
 # If you want to allow non-ASCII filenames set this variable to true.
 allownonascii=$(git config --bool hooks.allownonascii)
-
-# Redirect output to stderr.
-exec 1>&2
-
+exec 1>&2 # Redirect output to stderr.
 # Cross platform projects tend to avoid non-ASCII filenames; prevent
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
 	test $(git diff --cached --name-only --diff-filter=A -z $against |
 	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
 then
-	cat <<\EOF
-Error: Attempt to add a non-ASCII file name.
-
-This can cause problems if you want to work with people on other platforms.
-
-To be portable it is advisable to rename the file.
-
-If you know what you are doing you can disable this check using:
-
-  git config hooks.allownonascii true
-EOF
+	echo "[Error] attempt to add a non-ASCII file name."
 	exit 1
 fi
-
-# If there are whitespace errors, print the offending file names and fail.
-# exec git diff-index --check --cached $against --
+echo "===== pre-commit passes ===== "
